Models/Cliente.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace interfazRobot.Models
{
    public class Cliente
    {
        public int IdCliente { get; set; }
        [Required]
        [StringLength(100)]
        public string Nombre { get; set; }
        [Required]
        [StringLength(10)]
        public int Dui { get; set; }
        [Required]
        [StringLength(17)]
        public string Nit { get; set; }
        [Required]
        [StringLength(250)]
        public string Correo { get; set; }
    }
}

Controllers/ClientesController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using interfazRobot.Models;
namespace interfazRobot.Controllers
{
    public class ClientesController : Controller
    {
        public IActionResult Index()
        {
            Cliente c1 = new Cliente() { 
                IdCliente = 1,
                Nombre = "alexander",
                Dui = 1234567,
                Nit = "123213",
                Correo = "a@gmail.com",
            };
            List<Cliente> lc = new List<Cliente>() {
                new Cliente()
                {
                    IdCliente = 2,
                    Nombre = "mayda",
                    Dui = 1234567,
                    Nit = "123213",
                    Correo = "m@gmail.com",
                },
                new Cliente()
                {
                    IdCliente = 3,
                    Nombre = "gabriel",
                    Dui = 1234567,
                    Nit = "123213",
                    Correo = "g@gmail.com",
                }
            };
            lc.Add(c1);
            ViewBag.listaClientes = lc;
            return View();
        }
        public IActionResult Modificar()
        {
            return View();
        }
        public IActionResult Eliminar()
        {
            return View();
        }
    }
}

Views/Clientes/Index.cshtml
@model Cliente
<h2>Este es un formulario para adicionar un cliente a la lista</h2>
<div>
    <form action="/" method="post">

    </form>
</div>

<h2>
    Este es la vista lista de clientes
</h2>
<table class="table table-bordered">
    <thead>
        <tr>
            <td>ID</td>
            <td>Nombre</td>
            <td>DUI</td>
            <td>NIT</td>
            <td>Correo</td>
            <th colspan="2"></th>
        </tr>
    </thead
    <tbody>
        @foreach (Cliente item in ViewBag.listaClientes)
        {
        <tr>
            <td>@item.IdCliente</td>
            <td>@item.Nombre</td>
            <td>@item.Dui</td>
            <td>@item.Nit</td>
            <td>@item.Correo</td>
            <td> <a asp-controller="Clientes" asp-action="Modificar" asp-route-id="@item.IdCliente">Modificar</a> </td>
            <td> <a asp-controller="Home" asp-action="Privacy">Eliminar</a> </td>
        </tr>
        }
    </tbody>
</table>

Views/Clientes/Modificar.cshtml
<h2>Hola desde modificar cliente jajaja</h2>